### ISSUE TITLE
L1b scripts ran without errors but provided no output

### ISSUE THREAD

**Issue by hainguyent** [UMC-Utrecht-RWE/ConcePTION-Level1b#5]
Hi @t-andresvaz and @relbersumcu 
I've just run the L1b scripts. The to_run.R script finished without errors but I don't see any output in the g_output folder. The last few lines in the R console look like this: 
![image](https://user-images.githubusercontent.com/98932411/184680573-27889934-5b7a-4012-a89e-c05c5a640038.png)
Is there anything I've missed?

Thanks,

Hai

**Comment by t-andresvaz** [comment]
Hello @hainguyent 
Just to make sure, did you change values for StudyName and "path_to_fill" variables (to_run.R lines 14 and 17)?

**Comment by hainguyent** [comment]
Hi @t-andresvaz 
I have changed the StudyName and GetCountsColumns as per the instructions. I don't think it mentioned anything about path_to_fill. What should I change path_to_fill to please? 
Thanks,
Hai

**Comment by relbersumcu** [comment]
@t-andresvaz @hainguyent I would advise to use the path_to_fill. The folder structure differs per DAP since it differs for VAC4EU compared to the UMCU enviroment.

If you use path_to _fill you need to fill the location of the CDM files using a path. Then you set StudyName to NULL (StudyName <- NULL)

**Comment by hainguyent** [comment]
@relbersumcu @t-andresvaz I changed the path_to_fill and it worked! Thank you very much! :D

**Comment by t-andresvaz** [comment]
Nice! I am closing this issue now!
